version: "3.8"

services:
  frontend:
    image: es-next-frontend
    ports:
      - "3000:3000"
    # Outras configurações do frontend...

  laravel:
    image: es-next-laravel
    ports:
      - "9000:9000"
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8989:8989"
    # Outras configurações do Nginx...

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
