version: "3.8"

services:
  # Frontend React/Next.js
  frontend:
    image: es-next-frontend
    build:
      context: ./prototipobase
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - laravel-network

  # Laravel backend
  laravel:
    image: es-next-laravel
    build:
      context: ./laravel # Caminho para o diretório do seu backend Laravel
    ports:
      - "9000:9000" # A porta do Laravel dentro do contêiner
    volumes:
      - ./laravel:/var/www # Mapeia os arquivos do Laravel para o contêiner
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - laravel-network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Porta externa para acessar o Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Arquivo de configuração do Nginx
      - ./laravel:/var/www # Diretório Laravel
    depends_on:
      - laravel
    networks:
      - laravel-network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # Porta para acessar o PhpMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - laravel-network

  # Banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Porta do MySQL
    volumes:
      - db_data:/var/lib/mysql # Volume persistente do banco de dados
    networks:
      - laravel-network

# Volumes
volumes:
  db_data:

# Redes
networks:
  laravel-network:
    driver: bridge
